name: GitHub Actions Demo
on:
  push:
    branches:
      - development

jobs:

  Deploy-To-Stage:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run Eslint
        run: npm run lint

      - name: Run TypeChecker
        run: npm run typecheck

      - name: Run Test
        run: npm run test

